### ISSUE TITLE
Fix: Duplicate User class definitions in XUnit.Samples - namespace conflict

### ISSUE THREAD

**Issue by hnidboubker** [hnidboubker/PeasyPilot#23]
## Problem

Compilation error CS1503: Argument type mismatch due to duplicate `User` class definitions

**Error:**
```
UserServiceXUnitTests.cs(106,38): error CS1503: 
Cannot convert argument of type 'PeasyPilot.XUnit.Samples.Tests.User' 
to 'PeasyPilot.XUnit.Samples.Models.User'
```

## Root Cause

Two `User` classes exist in different namespaces:
- `PeasyPilot.XUnit.Samples.Tests.User` (in UserRepositoryIntegrationTests.cs)
- `PeasyPilot.XUnit.Samples.Models.User` (in Models/ folder)

This causes type mismatch when UserServiceXUnitTests tries to use User objects.

## Solution

Consolidate to single User model:
1. Keep User in `PeasyPilot.XUnit.Samples.Models.User`
2. Remove User from Tests namespace
3. Add proper using directive in test files

## Impact

- 21 compilation errors
- Blocks build on all frameworks (net8.0, net9.0, net10.0)
- Related to Issue #22
