### ISSUE TITLE
[P2.1] Create NAssert Alias (PeasyPilot.NUnit)

### ISSUE THREAD

**Issue by hnidboubker** [hnidboubker/PeasyPilot#68]
## P2.1: Create NAssert alias

**Parent:** Phase 2: Core Implementation (#63)  
**Duration:** 1 day  
**Agent:** Can be parallel with P2.2, P2.3

---

## Tasks

- [ ] Create file `src/PeasyPilot.NUnit/NAssert.cs`
- [ ] Implement NAssert static class
  - [ ] Forward all NUnit.Framework.Assert methods
  - [ ] Support all common assertion signatures
  - [ ] Equal, NotEqual, True, False, Null, NotNull
  - [ ] Throws, ThrowsAsync, DoesNotThrow
  - [ ] Contains, AreEqual, Greater, Less, etc.
  
- [ ] Add XML documentation
  - [ ] Summary for each method
  - [ ] Example usage
  - [ ] Exception documentation
  
- [ ] Test compilation
  - [ ] dotnet build on net8.0, net9.0, net10.0
  - [ ] No warnings (except XML docs)
  - [ ] IntelliSense appears correctly

- [ ] Create git branch
  - [ ] Branch: `feature/nunit-assert-alias`
  - [ ] Commit: "feat(nunit): Add NAssert alias for framework clarity"

## Acceptance Criteria

- [ ] NAssert.cs created with all common methods
- [ ] XML docs complete
- [ ] Builds on all frameworks
- [ ] Branch pushed
- [ ] No compilation errors

**Deliverable:** NAssert.cs implementation

**Comment by hnidboubker** [comment]
## ✅ P2.1 READY_FOR_COMMIT

### Deliverables
- ✅ src/PeasyPilot.NUnit/NAssert.cs created
- ✅ 30+ NUnit assertion methods forwarded
  - Equal, NotEqual, True, False, Null, NotNull
  - Throws, ThrowsAsync, DoesNotThrow, DoesNotThrowAsync
  - Greater, Less, GreaterOrEqual, LessOrEqual
  - Same, NotSame, IsInstanceOf, IsNotInstanceOf
  - IsEmpty, IsNotEmpty, Contains, DoesNotContain
  - That (Constraint model), Fail
- ✅ XML documentation complete for all methods
- ✅ Branch created: `feature/nunit-assert-alias`

### Status
- Build: In progress (multi-framework: net8.0, net9.0, net10.0)
- Tests: Awaiting build completion
- Commit: Staged (awaiting human git push)

### Next Step
Human needs to:
```bash
git add src/PeasyPilot.NUnit/NAssert.cs
git commit -m "feat(nunit): Add NAssert alias for framework clarity"
git push origin feature/nunit-assert-alias
```

Once build/tests pass, NAssert is ready for PR to main.
